# Generated by Django 4.2.16 on 2026-04-20 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to=music.models.album_cover_path)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('track_number', models.PositiveIntegerField(default=1)),
                ('audio_file', models.FileField(upload_to=music.models.track_upload_path)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Populated automatically from audio file', null=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('composer', models.CharField(blank=True, max_length=300)),
                ('lyricist', models.CharField(blank=True, max_length=300)),
                ('isrc', models.CharField(blank=True, help_text='International Standard Recording Code (e.g. US-S1Z-99-00001)', max_length=20)),
                ('bpm', models.PositiveIntegerField(blank=True, help_text='Beats per minute', null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ['track_number', 'title'],
            },
        ),
    ]
