# Generated by Django 4.2.16 on 2026-07-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriberprofile_temporary_access_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='navidrome_access_error',
            field=models.BooleanField(default=False),
        ),
    ]
