# Generated by Django 4.2.16 on 2026-07-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_subscriberprofile_navidrome_access_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='library_access_granted',
            field=models.BooleanField(default=False, help_text="Whether we've actually granted this user Navidrome library access. Tracked separately from subscription_status so staff can grant/revoke manually."),
        ),
    ]
