# Generated by Django 4.2.16 on 2026-07-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_application_into_profile'),
        ('subscribers', '0004_subscriberprofile_library_access_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Whether Stripe is set to cancel this subscription at current_period_end instead of automatically renewing it.'),
        ),
        migrations.AddField(
            model_name='subscriberprofile',
            name='designated_artist',
            field=models.ForeignKey(blank=True, help_text="The artist who receives 90% of this subscriber's fee.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporters', to='accounts.artistprofile'),
        ),
        migrations.CreateModel(
            name='SubscriptionStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('artist', 'Artist (free access)'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='subscribers.subscriberprofile')),
            ],
            options={
                'verbose_name': 'Subscription Status Change',
                'verbose_name_plural': 'Subscription Status Changes',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistDesignationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation_changes', to='accounts.artistprofile')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_designation_history', to='subscribers.subscriberprofile')),
            ],
            options={
                'verbose_name': 'Artist Designation Change',
                'verbose_name_plural': 'Artist Designation Changes',
                'ordering': ['-changed_at'],
            },
        ),
    ]
